=== liuyun1995/CodeBuilder/src/main/resources/codebuilder.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT codeBuilder (properties?, jdbcDriver, context+)>

<!ELEMENT jdbcDriver EMPTY>
<!ATTLIST jdbcDriver location CDATA #REQUIRED>

<!ELEMENT context (jdbcConnection, tables+)>
<!ATTLIST context id ID #REQUIRED>

<!ELEMENT jdbcConnection EMPTY>
<!ATTLIST jdbcConnection driverClass CDATA #REQUIRED
                         connectionURL CDATA #REQUIRED
                         userId CDATA #IMPLIED
                         password CDATA #IMPLIED>

<!ELEMENT tables (javaModel?, javaMapper?, xmlMapper?)>
<!ATTLIST tables tableName ID #REQUIRED
                 targetProject CDATA #IMPLIED
                 targetPackage CDATA #IMPLIED>
                 
<!ELEMENT javaModel EMPTY>
<!ATTLIST javaModel targetProject CDATA #IMPLIED
                    targetPackage CDATA #IMPLIED>

<!ELEMENT javaMapper EMPTY>
<!ATTLIST javaMapper targetProject CDATA #IMPLIED
                     targetPackage CDATA #IMPLIED>

<!ELEMENT xmlMapper EMPTY>
<!ATTLIST xmlMapper targetProject CDATA #IMPLIED
                    targetPackage CDATA #IMPLIED>

=== liuyun1995/CodeBuilder/src/test/resources/MySqlConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE codeBuilder SYSTEM "codebuilder.dtd">
<codeBuilder>

    <jdbcDriver location="E:\Tools\mybatisGenerator\mysql-connector-java-5.1.6.jar"/>
    
    <context id="mysql">
		<jdbcConnection driverClass="com.mysql.jdbc.Driver"
                        connectionURL="jdbc:mysql://192.168.7.54:8635/srm_interface" 
                        userId="itf"
                        password="|1|nxlc6h0IKF7DMfSq64Z2IsXB7kc=|" />
        
        <tables tableName="pur_purchase_info_records" targetProject="E:\CodeBuilder" targetPackage="mysql"/>
		<tables tableName="itf_fnd_coop_vendor_exp" targetProject="E:\CodeBuilder" targetPackage="mysql"/>
		<tables tableName="itf_pur_rfx_vendor_allot" targetProject="E:\CodeBuilder" targetPackage="mysql"/>
		<tables tableName="itf_pur_vendors" targetProject="E:\CodeBuilder" targetPackage="mysql"/>
		
    </context>
	
</codeBuilder>
